# Changes here will be overwritten by Copier
_commit: v0.4.1
_src_path: https://github.com/dalito/linkml-project-copier
add_example: true
copyright_year: '2025'
email: smoxon@lbl.gov
full_name: Sierra Moxon
gh_action_docs_preview: true
gh_action_pypi: true
github_org: sierra-moxon
license: MIT
project_description: A set of LinkML enumerations representing common units used in
    scientific research.
project_name: Unified Measurement Ontology
project_slug: unified_measurement_ontology

